In [ ]:
import numpy as np

array=np.array([1, 2, 3, 4])
print(array)
zero=np.zeros((2,3))
ones=np.ones((3,2))
print(zero)
print(ones)
arrange=np.arange(0,10,2)
lin=np.linspace(0,1,4).reshape(2,2)
print(arrange)
print(lin)  

print(lin.shape, lin.dtype, lin.ndim, lin.size, lin.itemsize, lin.nbytes)

array[-1]=10
print(array)

lin[1,1]=5
print(lin)
print(lin.sum(), lin.min(), lin.max(), lin.mean(), lin.std())
print(lin[:,1])
print(lin[1,:])
print(lin[lin>2])

print(array*2)
print(array**2)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[[0.         0.33333333]
 [0.66666667 1.        ]]
(2, 2) float64 2 4 8 32
[ 1  2  3 10]
[[0.         0.33333333]
 [0.66666667 5.        ]]
6.0 0.0 5.0 1.5 2.034425935955617
[0.33333333 5.        ]
[0.66666667 5.        ]
[5.]
[ 2  4  6 20]
[  1   4   9 100]


In [19]:
print(lin.sum(axis=0))
print(lin.sum(axis=1))

[0.66666667 5.33333333]
[0.33333333 5.66666667]


In [ ]:
print(np.isnan(array[0]))

# Slicing ????
print(lin[1:4])

False
[[0.66666667 5.        ]]


In [ ]:
#### EXO1 ####

#Crée un tableau NumPy contenant les nombres de 1 à 10.
T=np.arange(1,11,1)
print(T)
#Multiplie tous les éléments par 3 et affiche le résultat.
print(T*3)
#Calcule la somme, la moyenne et l’écart-type du tableau
print("somme",T.sum())
print("moyenne",T.mean())
print("ecart-type",T.std())
#Sélectionne uniquement les nombres supérieurs à 5 et affiche-les.
print(T[T>5])

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  6  9 12 15 18 21 24 27 30]
somme 55
moyenne 5.5
ecart-type 2.8722813232690143
[ 6  7  8  9 10]


In [66]:
#### EXO2 ####

#Crée un tableau 2x3 contenant les nombres de 1 à 6.
T_2D=np.arange(1,7,1).reshape(2,3)
print(T_2D)
#Affiche sa forme (shape) et sa taille (size).
print("shape:",T_2D.shape," size:",T_2D.size)
#Calcule la somme des lignes et la somme des colonnes.
print("somme des lignes:",T_2D.sum(axis=1),"somme des colonnes:",T_2D.sum(axis=0))
#Remplace tous les éléments supérieurs à 4 par 0.
T_2D[T_2D>4]=0
print(T_2D)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)  size: 6
somme des lignes: [ 6 15] somme des colonnes: [5 7 9]
[[1 2 3]
 [4 0 0]]


In [ ]:
#### EXO3 ####

import pandas as pd
#Crée une Series avec les notes : [12, 15, 18, 10, 14] et les étiquettes ["Math", "Physique","Chimie", "Info", "Bio"].
N=[12, 15, 18, 10, 14]
S=pd.Series(N,index=["Math", "Physique","Chimie", "Info", "Bio"])
print(S)

#Affiche la note de "Chimie".
print(S["Chimie"])
#Calcule la moyenne des notes
print(S.mean())
#Sélectionne les matières dont la note est supérieure ou égale à 15.
print(S[S>15])
print(S[S.values>15])

Math        12
Physique    15
Chimie      18
Info        10
Bio         14
dtype: int64
18
13.8
Chimie    18
dtype: int64
Index(['Chimie'], dtype='object')


In [ ]:
#### EXO4 ####

#Crée un DataFrame avec les colonnes :....
## a partir d'un dictionnaire de listes
data={'Nom':['Ali','Sara','Youssef'],
      'Age':[23,21,22],
      'Ville':['Tunis','Sfax','Carthage']}
df1=pd.DataFrame(data)
print(df1)

## a partir d'un dictionnaire de Series
Serie={'Nom':pd.Series(['Ali','Sara','Youssef']),
       'Age':pd.Series([23,21,22]),
       'Ville':pd.Series(['Tunis','Sfax','Carthage'])}
df=pd.DataFrame(Serie)
print(df)

## a partir des ndarray de numpy
arr=np.arange(12).reshape(4,3)
df=pd.DataFrame(arr,columns=['Nom','Age','Ville'],index=['L1','L2','L3','L4'])
print(df)

#Affiche uniquement la colonne Âge.
print("la colonne Age \n",df1['Age'])

#Sélectionne les lignes où l’âge est supérieur à 23.
print("les cols avec age>23\n",df1[df1['Age']>21])

#Ajoute une nouvelle colonne "Score" avec les valeurs [85, 90, 95].
df1['Score']=[85,90,95]
print(df1)

#Calcule l’âge moyen des personnes dans le DataFrame.
print("age moyen:",df1['Age'].mean())

#Ajoute une nouvelle colonne Âge+5 qui ajoute 5 à chaque âge
df1['Age+5']=df1['Age']+5
print(df1)

       Nom  Age     Ville
0      Ali   23     Tunis
1     Sara   21      Sfax
2  Youssef   22  Carthage
       Nom  Age     Ville
0      Ali   23     Tunis
1     Sara   21      Sfax
2  Youssef   22  Carthage
    Nom  Age  Ville
L1    0    1      2
L2    3    4      5
L3    6    7      8
L4    9   10     11
la colonne Age 
 0    23
1    21
2    22
Name: Age, dtype: int64
les cols avec age>23
        Nom  Age     Ville
0      Ali   23     Tunis
2  Youssef   22  Carthage
       Nom  Age     Ville  Score
0      Ali   23     Tunis     85
1     Sara   21      Sfax     90
2  Youssef   22  Carthage     95
age moyen: 22.0
       Nom  Age     Ville  Score  Age+5
0      Ali   23     Tunis     85     28
1     Sara   21      Sfax     90     26
2  Youssef   22  Carthage     95     27


In [ ]:
#### EXO5 ####

#Crée un DataFrame avec les ventes mensuelles :
data={'Mois':['Janvier','Février','Mars','Avril','Mai','Juin'],
      'Ventes':[1500,1800,1700,1600,2000,2100]}



